"""add current_step to research_runs

Revision ID: 3ef2445169b6
Revises: 1e11f07d6fa8
Create Date: 2026-08-14 10:13:07.309533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef2445169b6'
down_revision: Union[str, Sequence[str], None] = '1e11f07d6fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('current_step', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'current_step')
    # ### end Alembic commands ###
