"""add started_at to research_runs

Revision ID: d7e85d021935
Revises: f7aff35df56d
Create Date: 2026-08-20 16:58:19.235563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e85d021935'
down_revision: Union[str, Sequence[str], None] = 'f7aff35df56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'started_at')
    # ### end Alembic commands ###
